include:
  - local: helm-tests/template-tests/.gitlab-ci.yml
  - local: helm-tests/integration-tests/.gitlab-ci.yml
  - local: helm-tests/smoke-tests/.gitlab-ci.yml
  - local: helm-tests/examples-test/.gitlab-ci.yml

stages:
  - initialization
  - test.template
  - test.smoke
  - test.examples
  - test.integration
  - publish
  - push
  - release
  - final

default:
  before_script:
    - ci_scripts/before_script.sh
  services:
    - $PIPELINE_DEPS_REGISTRY/docker:18.09-dind
  image: $RUNNER_IMAGE_X86_64
################################################
# Default variables used by all jobs unless they
# are overridden by the job
#
#  - .5-1 cpu
#  - 1.9GB of memory with no elasticity
#  - poll timeout of 15 minutes (to release capacity)
################################################
variables:
  DOCKER_HOST: tcp://localhost:2375
  KUBERNETES_CPU_REQUEST: 500m
  KUBERNETES_CPU_LIMIT: 1000m
  KUBERNETES_MEMORY_REQUEST: 1900000000
  KUBERNETES_MEMORY_LIMIT: 1900000000
  KUBERNETES_POLL_TIMEOUT: 1200
################################################
# For Docker Compose Tests, provide a kubernetes
# sizing of:
#
#  - 95% of a cpu up to 4x (380%)
#  - 1.9g of memory with no elasticity
################################################
# variables:
#   KUBERNETES_CPU_REQUEST: 950m
#   KUBERNETES_CPU_LIMIT: 3800m
#   KUBERNETES_MEMORY_REQUEST: 1900000000
#   KUBERNETES_MEMORY_LIMIT: 1900000000

################################################
#   _____ _   _ _____ _______
#  |_   _| \ | |_   _|__   __|
#    | | |  \| | | |    | |
#    | | | . ` | | |    | |
#   _| |_| |\  |_| |
#  |_____|_| \_|_____|  |_|
#
################################################
intel.i.chartlinter:
  stage: initialization
  script:
    - ci_scripts/helm_chart_linter.sh
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^workspace.*/
      - $CI_COMMIT_MESSAGE =~ /\[skip build\]/
      - $CI_COMMIT_TAG

intel.i.shfmt:
  stage: initialization
  script:
    - ci_scripts/shfmt.sh --diff
  rules:
    - changes:
        - ci_scripts/*
      when: always

################################################
#   _____       _     _ _     _
#  |  __ \     | |   | (_)   | |
#  | |__) |   _| |__ | |_ ___| |__
#  |  ___/ | | | '_ \| | / __| '_ \
#  | |   | |_| | |_) | | \__ \ | | |
#  |_|    \__,_|_.__/|_|_|___/_| |_|
#
################################################

p.github:
  stage: push
  before_script:
    - git config --global user.name "${GITLAB_USER}"
    - git config --global user.email "${GITLAB_USER}@pingidentity.com"
  script:
    - git --version
    - ci_scripts/push_to_github.sh
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^master$/'
    - if: $RELEASE == "true"

################################################
#  ____      _
# |  _ \ ___| | ___  __ _ ___  ___
# | |_) / _ \ |/ _ \/ _` / __|/ _ \
# |  _ <  __/ |  __/ (_| \__ \  __/
# |_| \_\___|_|\___|\__,_|___/\___|
#
################################################

r.release:
  stage: release
  before_script:
    - git config --global user.name "${GITLAB_USER}"
    - git config --global user.email "${GITLAB_USER}@pingidentity.com"
  script:
    - ci_scripts/release_charts.sh
  rules:
    - if: $RELEASE == "true" && '$CI_COMMIT_TAG !~ "/^$/"'

################################################
#   ______ _____ _   _          _
#  |  ____|_   _| \ | |   /\   | |
#  | |__    | | |  \| |  /  \  | |
#  |  __|   | | | . ` | / /\ \ | |
#  | |     _| |_| |\  |/ ____ \| |____
#  |_|    |_____|_| \_/_/    \_\______|
################################################

clean-k8s:
  stage: final
  script:
    - ci_scripts/cleanup_kubernetes.sh
  when: always

delete-old-k8s:
  stage: final
  script:
    - ci_scripts/cleanup_old_kubernetes.sh
  when: always