#######################################################################
# Ping Identity DevOps Chart
########################################################################
apiVersion: v2
name: ping-devops
########################################################################
# 0.11.1 - Refer to http://helm.pingidentity.com/release-notes/currentRelease
########################################################################
version: 0.11.1
description: Ping Identity helm charts - 12/03/2024
type: application
home: https://helm.pingidentity.com/
icon: https://helm.pingidentity.com/img/logos/ping.png
appVersion: "2411"
