################################################
#                  EXAMPLE TESTS
################################################

intel.everything.example:
  stage: test.examples
  before_script:
    - git clone https://github.com/pingidentity/pingidentity-devops-getting-started.git
    - cat pingidentity-devops-getting-started/30-helm/everything.yaml helm-tests/examples-test/everything/teststeps/everythingteststeps.yaml > helm-tests/examples-test/everything/everything.yaml
  script:
    - ci_scripts/run_helm_integration.sh --test-directory examples-test --integration-test everything --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $NIGHTLY == "true"

intel.pd-backup-sidecar.example:
  stage: test.examples
  before_script:
    - git clone https://github.com/pingidentity/pingidentity-devops-getting-started.git
    - cat pingidentity-devops-getting-started/30-helm/pingdirectory-backup/pingdirectory-periodic-backup.yaml helm-tests/examples-test/pd-backup-sidecar/teststeps/pd-backup-sidecar.yaml > helm-tests/examples-test/pd-backup-sidecar/pd-backup-sidecar.yaml
  script:
    - ci_scripts/run_helm_integration.sh --test-directory examples-test --integration-test pd-backup-sidecar --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $NIGHTLY == "true"

intel.pingaccess-cluster.example:
  stage: test.examples
  before_script:
    - git clone https://github.com/pingidentity/pingidentity-devops-getting-started.git
    - cat pingidentity-devops-getting-started/30-helm/pingaccess-cluster.yaml helm-tests/examples-test/pingaccess-cluster/teststeps/pingaccess-cluster.yaml > helm-tests/examples-test/pingaccess-cluster/pingaccess-cluster.yaml
    - perl -i -p -e 's/"insert domain name here"/ping-devops.com/g' helm-tests/examples-test/pingaccess-cluster/pingaccess-cluster.yaml
  script:
    - ci_scripts/run_helm_integration.sh --test-directory examples-test --integration-test pingaccess-cluster --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $NIGHTLY == "true"

intel.pingdirectory.example:
  stage: test.examples
  before_script:
    - git clone https://github.com/pingidentity/pingidentity-devops-getting-started.git
    - cat pingidentity-devops-getting-started/30-helm/pingdirectory.yaml helm-tests/examples-test/pingdirectory/teststeps/pingdirectory.yaml > helm-tests/examples-test/pingdirectory/pingdirectory.yaml
  script:
    - ci_scripts/run_helm_integration.sh --test-directory examples-test --integration-test pingdirectory --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $NIGHTLY == "true"