# This test covers setting autoscaling.
### SECTION:PARAMETERS ###
releaseName: autoscaling
# Set skipTest to true to make the script skip this test
skipTest: false
### SECTION:VALUES ###
# Set typical Helm values here
global:
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
  clustering:
    autoscaling:
      enabled: true

pingfederate-admin:
  enabled: true

pingfederate-engine:
  enabled: true
  workload:
    type: StatefulSet

pingaccess-engine:
  enabled: true

pingdataconsole:
  enabled: true

pingauthorize:
  enabled: true

pingauthorizepap:
  enabled: true

pingcentral:
  enabled: true

pingdelegator:
  enabled: true

### SECTION:EXPECTED ###

# Validate that expected Horizontal Pod Autoscaler are generated
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-pingfederate-admin
spec:
  scaleTargetRef:
    kind: Deployment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-pingfederate-engine
spec:
  scaleTargetRef:
    kind: StatefulSet
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-pingaccess-engine
spec:
  scaleTargetRef:
    kind: Deployment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-pingdataconsole
spec:
  scaleTargetRef:
    kind: Deployment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-pingauthorize
spec:
  scaleTargetRef:
    kind: Deployment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-pingauthorizepap
spec:
  scaleTargetRef:
    kind: Deployment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-pingcentral
spec:
  scaleTargetRef:
    kind: Deployment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-pingdelegator
spec:
  scaleTargetRef:
    kind: Deployment
---
