# This test covers including topologySpreadConstraints in your workload values.

### SECTION:PARAMETERS ###
# If the releaseName parameter is not set, then a default release name
# matching the name of the file (without the extension) will be used.
releaseName: topologytest
# Set skipTest to true to make the script skip this test
skipTest: false
### SECTION:VALUES ###
pingdataconsole:
  enabled: true
global:
  workload:
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: node
      whenUnsatisfiable: ScheduleAnyway
      matchLabels:
        foo: bar
### SECTION:EXPECTED ###
# Validate that topologySpreadConstraints is set in the PDC Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topologytest-pingdataconsole
spec:
  template:
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: ScheduleAnyway
        matchLabels:
          foo: bar
---